### ISSUE TITLE
On Receive RBTC appear (YOUR CURRENT ETHEREUM ADDRESS)

### ISSUE THREAD

**Issue by bitcoinuser** [liquality/wallet#19]
On Receive RBTC appear (YOUR CURRENT ETHEREUM ADDRESS).

Should appear: (YOUR CURRENT ROOTSTOCK ADDRESS).

![Captura de tela de 2020-12-15 12-23-09](https://user-images.githubusercontent.com/1178856/102235022-a78baa80-3ed0-11eb-8362-f254d9b94930.png)

**Comment by gr0kchain** [comment]
This has been resolved and it in the latest development branch
