### ISSUE TITLE
Add BitPRO asset on manage assets list

### ISSUE THREAD

**Issue by bitcoinuser** [liquality/wallet#30]
Hi,

Please add BitPRO asset on manage assets list, instead of Custom token.

Contract: https://blockscout.com/rsk/mainnet/tokens/0x440cd83C160de5C96DDb20246815EA44C7Abbca8/token-transfers

Liquality 0.11

**Comment by bradleySuira** [comment]
Fixed now in the 0.13.0 version

**Comment by bitcoinuser** [comment]
Needs to add Bitpro icon. Thanks.

**Comment by bitcoinuser** [comment]
Ignore, it's because I had added Bitpro as custom token. I see now that I can add the new one from manage assets.
