### ISSUE TITLE
v0.13.0 fails to inject web3 when RSK asset is selected

### ISSUE THREAD

**Issue by creed-victor** [liquality/wallet#40]
Steps to reproduce:

1.  Set Default Web3 Wallet toggle to enabled
2. Set Web3 Asset to RSK
3. Open browser dev tools and write `window.ethereum` to console
4. Receive error: `Uncaught ReferenceError: ethereum is not defined`

Also there is visible error once console opened:

```
Error handling response: TypeError: Cannot read property 'mainnet' of undefined
    at chrome-extension://kpfopkelmapcoipemfendmdcghnegimn/js/content-script.js:154:177395
```

**Comment by simonlapscher** [comment]
Fixed in 0.14.0
