### ISSUE TITLE
Liquality doesn't list the transactions received of contract call, only recognize the balance

### ISSUE THREAD

**Issue by bitcoinuser** [liquality/wallet#41]
Hi,

Recently I exchanged RBTC to BPRO using moneyonchain.com plataform. On liquality I see the RBTC transaction sending the funds. The transaction was this: https://explorer.rsk.co/tx/0x7dc7ce5cf06aadae17c48ef294eb36fb139f16ba348bb0b50497cdd0521cfd25?__ctab=Transaction

But on Liquality on Birpro asset I see only the balance I received but not the transaction of the Bitpro received. The transaction received should be this one: https://explorer.rsk.co/tx/0x7dc7ce5cf06aadae17c48ef294eb36fb139f16ba348bb0b50497cdd0521cfd25?__ctab=Token%20Transfers

Liquality should show on Bipro asset the transaction received of the value 0.96640397...BITP

**Comment by bradleySuira** [comment]
Hi @bitcoinuser thanks for the report, for now our wallet doesn't; have support for received transactions but we have it in the backlog. I will close this issue for now.

Regards!
