### ISSUE TITLE
Some icons are smaller than others

### ISSUE THREAD

**Issue by bitcoinuser** [liquality/wallet#42]
Some icons are smaller than others

See:

![Liquality](https://user-images.githubusercontent.com/1178856/105606448-492bd480-5d78-11eb-849d-4d38e85a9a13.jpg)

**Comment by bradleySuira** [comment]
Hi @bitcoinuser thanks for the info, we will check this issue and find a way to show all at the same size, at the end are the same size but the icon itself has like a space used for some parts of the icon for example check RIF (the leaf) vs DOC. 

Regards!
