### ISSUE TITLE
@liquality/hw-web-bridge library not found

### ISSUE THREAD

**Issue by alicantutumlu** [liquality/wallet#628]
When I try to install dependencies, it gives an error like "npm ERR! 404 Not Found - GET https://registry.npmjs.org/@liquality/hw-web-bridge/-/hw-web-bridge-0.1.1.tgz - Not found"

Is this dependency up? Is there any other way to integrate it?

**Comment by beemi** [comment]
This is fixed with 0.1.2 in latest dev branch

**Comment by beemi** [comment]
No longer an issue, closing this
