### ISSUE TITLE
Signed transaction hash is missing

### ISSUE THREAD

**Issue by tiltom** [liquality/wallet#916]
We have integrated Liquality in two of our dapps: Babelfish and [Sovryn](https://live.sovryn.app/).

On both of them, we have the same problem - a transaction hash is not present after signing. We use [`sendSignedTransaction`](https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#sendsignedtransaction) for signing transactions and everything works fine with `Metamask` and other wallets we support. With Liquality, we get the following error:
<img width="684" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/14878713/200006531-435dbbb0-9bf9-4399-aeb8-763491978d0a.png">

This basically prevents us from tracking transactions' state and even though they are successful and we see them in the Liquality wallet, our UIs consider those transactions either failures (Babelfish) or display them without a tx hash and our transaction status is stuck in "Processing" state (Sovryn).

**Comment by stephien** [comment]
A fix for Linear https://linear.app/liquality/issue/COR-57 was included in version [0.79.0](https://github.com/liquality/wallet/releases/tag/v0.79.0) that is now available in the Chrome Store at https://liquality.io

@tiltom could you please check if the above error has been solved in the 0.79.0 version of the Liquality Wallet extension?

**Comment by tiltom** [comment]
@stephien thanks for the response, I just tested both dapps and they're working fine with version 0.79.0 so I am closing the issue.
